### ISSUE TITLE
query.update synchronize_session does not support bool

### ISSUE THREAD

**Issue by dbanty** [dropbox/sqlalchemy-stubs#116]
When passing a boolean to the `synchronize_session` param of `update` or `delete`, mypy complains with 
> Argument "synchronize_session" to "update" of "Query" has incompatible type "bool"; expected "str"

If you look in [the docs](https://docs.sqlalchemy.org/en/13/orm/query.html?highlight=synchronize_session#sqlalchemy.orm.query.Query.update.params.synchronize_session), `False` is a valid value.

**Comment by ilevkivskyi** [comment]
Fixed by https://github.com/dropbox/sqlalchemy-stubs/pull/117
