### ISSUE TITLE
Allow automatically named indices

### ISSUE THREAD

**Issue by ludaavics** [dropbox/sqlalchemy-stubs#124]
Hi,

mypy rejects `Index(None, "column1", "column2")` as it [expects](https://github.com/dropbox/sqlalchemy-stubs/blob/master/sqlalchemy-stubs/sql/schema.pyi#L304) a string. However, we are allowed to pass `None` if we want to use the [automated naming](https://alembic.sqlalchemy.org/en/latest/naming.html#integration-of-naming-conventions-into-operations-autogenerate)

Thanks!

**Comment by ilevkivskyi** [comment]
Thanks for reporting! PRs welcome.
