### ISSUE TITLE
Data type for Numeric column should be Decimal, not float

### ISSUE THREAD

**Issue by martinstein** [dropbox/sqlalchemy-stubs#131]
The official SQLAlchemy documentation for the column type `Numeric` says:

> This type returns Python decimal.Decimal objects by default, unless the Numeric.asdecimal flag is set to False, in which case they are coerced to Python float objects.

https://docs.sqlalchemy.org/en/13/core/type_basics.html#sqlalchemy.types.Numeric

Currently this is specified in sqltypes.pyi as `TypeEngine[float]` but by default the inner data type for Numeric should be `Decimal`, not `float`. That would be more in line with
* what the SQLAlchemy documentation says.
* how SQLAlchemy actually behaves.

The current approach reports typing errors even though the code is correct (due to the float/Decimal confusion) . Example to reproduce:

```python
from decimal import Decimal
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, Numeric

Base = declarative_base()


class Transaction(Base):
    __tablename__ = 'transactions'
    id = Column(Integer, primary_key=True)
    amount = Column(Numeric, nullable=False)


user = User(id=42, amount=Decimal(42))
```

This code is 100% correctly typed, but since the sqlalchemy-stubs use float instead of Decimal we receive a typing-error message that we shouldn't get:

```
mypy-sa-test.py:14: error: Incompatible type for "amount" of "User" (got "Decimal", expected "float")
```

**Comment by msullivan** [comment]
That seems plausible. Do you want to submit a PR?

I am worried about whether this will cause problems if a lot of existing code assumes float already, though? But if that is wrong, maybe that's a good thing

**Comment by martinstein** [comment]
Yes, happy to submit a PR and I agree that if existing code assumes float, fixing this will likely help those users to uncover a wrong type assumption.
I'm wondering: Is there a way to set up the type-stub so the type of the field depends on the value of the `asdecimal` argument of the Column? (which is True by default)

**Comment by dbanty** [comment]
Any word on when this will make it into a release?  Would save me quite a few `cast`s and `# type: ignore`s 😸

**Comment by ave2me** [comment]
I'm also very interested if there any news on when this fix will be included in a release.

**Comment by raychan** [comment]
Looks like this issue is fixed, can we release the fix?

**Comment by nick-bigger** [comment]
I'm also wondering when this fix will go in?

**Comment by ilevkivskyi** [comment]
I am going to make a release later today. Please test with current master to check if there are any issues.

**Comment by ilevkivskyi** [comment]
(closing the issue since IIUC this is fixed in master)
