### ISSUE TITLE
Question: Is it alive?

### ISSUE THREAD

**Issue by item4** [dropbox/sqlalchemy-stubs#141]
I want to make some PR but I think this repo is inactive. Is it alive or not?

**Comment by JukkaL** [comment]
It's still alive, though not as active as it used to be. We don't have a lot of bandwidth to review big or tricky PRs, however.

**Comment by item4** [comment]
@JukkaL OK. I will make just simple PR only

**Comment by ilevkivskyi** [comment]
Superseded with https://github.com/dropbox/sqlalchemy-stubs/issues/195 :-)
