### ISSUE TITLE
Question: What is the "sqltyping.py" good for?

### ISSUE THREAD

**Issue by MartinThoma** [dropbox/sqlalchemy-stubs#175]
It seems not to be used anywhere.

```
$ grep -rnI "sqltyping" *
setup.py:53:      py_modules=['sqlmypy', 'sqltyping'],
```

**Comment by ilevkivskyi** [comment]
It is a placeholder for introduction of mypy plugin specific types. It may be needed for something like https://github.com/dropbox/sqlalchemy-stubs/issues/9
