### ISSUE TITLE
Is the return-type of process_bind_param correct?

### ISSUE THREAD

**Issue by exhuma** [dropbox/sqlalchemy-stubs#212]
[here](https://github.com/dropbox/sqlalchemy-stubs/blob/55470ceab8149db983411d5c094c9fe16343c58b/sqlalchemy-stubs/sql/type_api.pyi#L95) the return type is defines as `typing_Text` and I'm not sure if that's correct. If I have the following type-decorator I get a typing error but the code works:

```
class DbInfiniteInt(TypeDecorator):  # type: ignore
    """
    A codec which maps a database integer value to "MaybeInfiniteInt"
    """

    impl = Integer

    def process_bind_param(
        self, 
        value: Optional[MaybeInfiniteInt],
        dialect: Dialect,
    ) -> Optional[int]:  # <-- mypy complains about this return-type
        if value is None:
            return None
        if value.is_infinite():
            return -1
        return int(value)
```

**Comment by huonw** [comment]
I think you're right, that it's not. We've had to use `# type: ignore` on our `process_bind_param` functions. (I think this is a duplicate of #205 and #206.)

**Comment by exhuma** [comment]
You're right. It's a duplicate. I'm closing this in favour of #205
