### ISSUE TITLE
Support postgres uuid

### ISSUE THREAD

**Issue by kespindler** [dropbox/sqlalchemy-stubs#60]
I'm trying to get sqlalchemy-stubs to work with a larger set of types. This would include uuids and JSON, but also encompasses a question about how to effectively create custom subtypes for columns (e.g. an Email str subtype.)

```
from sqlalchemy.ext.declarative import declarative_base
from sqlalchemy import Column, Integer, String
from sqlalchemy.dialects.postgresql import UUID
from uuid import uuid4 as gen_uuid
from typing import NewType

Base = declarative_base()

# create NewTypes for uuids and emails so that my_email: Email = 'random string' fails.
Uuid = NewType('Uuid', str)
Email = NewType('Email', str)

def uuid4():
    return str(gen_uuid())


class UuidModel(Base):
    __abstract__ = True
    uuid = Column(UUID, primary_key=True, default=uuid4)


class User(UuidModel):
    __tablename__ = 'users'
    fico_score = Column(Integer, primary_key=True)
    first_name = Column(String)

user = User(fico_score=42, first_name='bob')
reveal_type(User.uuid)
reveal_type(user.uuid)
User.first_name.ilike('hi')
```

gives

```
script/test_model_typing.py:24: error: Revealed type is 'sqlalchemy.sql.schema.Column[Any]'
script/test_model_typing.py:25: error: Revealed type is 'Any'
```

I'd love to be able to support postgres uuids (and JSON too!) in our codebase. To accomplish this, I tried mimicking sqltypes.pyi by creating a file `sqlalchemy-stubs/dialects/postgresql/base.pyi` with contents

```
from typing import Type, NewType

from .type_api import TypeEngine as TypeEngine
from ..sql.sqltypes import _LookupExpressionAdapter


Uuid = NewType('Uuid', str)


class UUID(_LookupExpressionAdapter, TypeEngine[str]):
    __visit_name__: str = ...
    def get_dbapi_type(self, dbapi): ...
    @property
    def python_type(self) -> Type[Uuid]: ...
```

and importing it from  `sqlalchemy-stubs/dialects/postgresql/__init__.pyi` . That didn't seem to accomplish anything. I'd love some direction on the easiest way to contribute and add on to this great project.

**Comment by ilevkivskyi** [comment]
For example
```python
class PgUuid(TypeDecorator[Uuid]):
    impl = UUID
```
You can also try making it generic to work with multiple `NewType`s, I hope you can figure it on your own.

**Comment by kespindler** [comment]
Is there a way to include it in the `.py` file instead of separate `.pyi` file? I tried that method within the `.py` file, but I got

```
  File "./debtsy/lib/sqlalchemy.py", line 36, in <module>
    class PgUuid(sqltypes.TypeDecorator[Uuid]):
TypeError: 'VisitableType' object is not subscriptable
```

I also tried this:

```
class PgUuid(UUID):  # type: PgUuid(sqltypes.TypeDecorator[Uuid], UUID)
    pass
```

but got a `error: misplaced type annotation` error.

I really appreciate your help. I'd like to submit some quick docs as well as a few other fixes once I figure this out!

**Comment by ilevkivskyi** [comment]
> Is there a way to include it in the `.py` file instead of separate `.pyi` file?

https://mypy.readthedocs.io/en/latest/common_issues.html#using-classes-that-are-generic-in-stubs-but-not-at-runtime
