### ISSUE TITLE
Latest version seems to break mypy

### ISSUE THREAD

**Issue by mehdigmira** [dropbox/sqlalchemy-stubs#63]
when running mypy on my project, I get this error:
```Error importing plugin sqlmypy```

When debugging a little bit, the problem seems to be here:
```
    def get_dynamic_class_hook(self, fullname: str) -> CB[DynamicClassDefContext]:
  File "/usr/lib/python3.5/typing.py", line 546, in __getitem__
    "Cannot subscript an existing Union. Use Union[u, t] instead.")
TypeError: Cannot subscript an existing Union. Use Union[u, t] instead.
```

**Comment by ilevkivskyi** [comment]
You need to update Python to a newer version (I think at least 3.5.2, but better just the latest 3.5 version).

**Comment by arusahni** [comment]
I have this same error on Python 3.7.2:

```
$ python --version
Python 3.7.2

$ mypy --version
mypy 0.670

$ pip show sqlalchemy-stubs
Name: sqlalchemy-stubs
Version: 0.1
Summary: SQLAlchemy stubs and mypy plugin
Home-page: https://github.com/dropbox/sqlalchemy-stubs
Author: Ivan Levkivskyi
Author-email: levkivskyi@gmail.com
License: MIT License
Location: /Users/aru/.virtualenvs/portal/lib/python3.7/site-packages
Requires: typing-extensions, mypy
Required-by:
```

In my `setup.cfg`:

```
[mypy]
plugins = sqlmypy
```

**Comment by ilevkivskyi** [comment]
You can't have the same error on Python 3.7.2 because that line of code simply doesn't exist in Python 3.7.2, can you post exactly the traceback you see?

**Comment by arusahni** [comment]
I'm sorry, I don't know how I missed the traceback portion of the OP's error.  I seem to be unable to generate a traceback?

```
$ mypy --tb package_name
setup.cfg:8: error: Error importing plugin 'sqlmypy'
```

**Comment by ilevkivskyi** [comment]
Do you have `sqlalchemy-stubs` and `mypy` installed in the same virtualenv?

**Comment by arusahni** [comment]
I do...  however, I discovered that, for whatever reason, my shell was using my global mypy.  Forcing a re-hash fixed things.  Sorry for the confusion!

**Comment by cdpath** [comment]
I fixed this issue by adding `sqlalchemy-stubs` explicitly in `.pre-commit-config.yaml`, like this:

```yaml
-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: 'v0.910'
    hooks:
    - id: mypy
      additional_dependencies:
        - 'pydantic'
        - 'sqlalchemy-stubs'
```
