### ISSUE TITLE
Release v0.2?

### ISSUE THREAD

**Issue by MattF-NSIDC** [dropbox/sqlalchemy-stubs#78]
Hello! Thanks for building this plugin and stubs! It's great to see more support for type-checked Python.

We hit a wall and needed to `#type: ignore` our `ForeignKeyConstraint` calls to get them to pass type checking. We found that a fix had been merged a couple months ago (#56), but is not yet released. We were deciding between either submoduling this repo so we could use the fix which is on `master` or just `#type: ignore`ing it, neither is really great. Could you guys please put out a v0.2 release for this library so we can clean that up? Thanks :)

**Comment by ilevkivskyi** [comment]
Yes, we are thinking about a release in couple weeks, likely mid-May. Unfortunately, we are busy with other (unrelated) things currently, so can't make a release sooner.

**Comment by glyph** [comment]
Hello from mid-May! 😄 Any chance that a release might be forthcoming soon?

**Comment by ilevkivskyi** [comment]
Oh, hi! There turned out to be much more "other things" than I thought. Hopefully I will came back to working on this next week (it is a bit harder than just pushing a new version on PyPI because we need to do an internal sync).

Sorry for a delay!

**Comment by glyph** [comment]
> Oh, hi! There turned out to be much more "other things" than I thought.

So it goes.

> Hopefully I will came back to working on this next week (it is a bit harder than just pushing a new version on PyPI because we need to do an internal sync).

Glad to hear it!

> Sorry for a delay!

No need to apologize - I'm sure there are tickets on the Twisted tracker from 2008 where I confidently assure someone that the fix will be done "next week" 😉 .

**Comment by glyph** [comment]
Anything that an external person might be able to do to move this along?

**Comment by ilevkivskyi** [comment]
OK, after huge delay I just released v0.2 on PyPI. Please try it and let me know if there are any issues!

**Comment by glyph** [comment]
Thanks so much @ilevkivskyi !
