### ISSUE TITLE
Is there a reason `selectinload` isn't a supported import currently?

### ISSUE THREAD

**Issue by ckarnell** [dropbox/sqlalchemy-stubs#83]
Using these stubs I get a type error when I import `from sqlalchemy.orm import selectinload` saying it's not a valid import. Is there a reason for this? I know it's a relatively knew feature.

Thanks for making these stubs by the way!

**Comment by ilevkivskyi** [comment]
> I know it's a relatively new feature.

This is exactly the case. We are still missing stubs for some recent features. If you have some time you can try using `stubgen` (tool that comes with mypy) to generate the missing stubs (this typically require a bit of manual work on auto-generated stubs).

**Comment by ckarnell** [comment]
@ilevkivskyi Hi, can I be added as a collaborator to this repo? I made a local branch to fix this issue but I'm not allowed to push it.
